version: '3.9'

services:
  app:
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - "./:/task_board"
    build: 
      context: .
      dockerfile: DockerFile
    env_file: .env
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"